In [1]:
import numpy as np
array1 = np.array([1,2,3,4,5])

In [2]:
array1.ndim

1

In [3]:
array2 = np.array([[1,2,3,4,5],
                  [6,7,8,9,0]])

In [4]:
array2.ndim

2

In [5]:
array2.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [6]:
array2.dtype

dtype('int64')

In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
np.empty((2,3,2))

array([[[  6.91610271e-310,   1.63476678e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(2,3)

array([2])

In [12]:
np.arange(2,2,4)

array([], dtype=int64)

In [13]:
array3 = np.array([1,2,3], dtype=np.float64)

In [14]:
array3

array([ 1.,  2.,  3.])

In [15]:
int_array = array3.astype(np.int64)

In [16]:
int_array

array([1, 2, 3])

In [17]:
numeric_strings = int_array.astype(np.string_)

In [18]:
numeric_strings

array([b'1', b'2', b'3'], 
      dtype='|S21')

In [19]:
int_arrays = np.arange(10)

In [20]:
calibers = np.array([.22,.34,.567,.123,.6789], dtype=np.float64)

In [21]:
int_arrays.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [22]:
int_arrays * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [23]:
int_arrays - int_arrays?

In [ ]:
int_arrays - int_arrays

In [24]:
int_arrays - int_arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
int_arrays - int_arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr = np.arange(10)

In [27]:
arr[5]

5

In [28]:
arr[5:8]

array([5, 6, 7])

In [29]:
arr[5:]

array([5, 6, 7, 8, 9])

In [30]:
arr[5:7] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12,  7,  8,  9])

In [32]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
arr2.ndim

2

In [34]:
arra3 = np.array([[[1,2,3],[1,2,3],[4,5,6],[7,8,9]]])

In [35]:
arra3

array([[[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
arra3.ndim

3

In [37]:
arra3[1:1]

array([], shape=(0, 4, 3), dtype=int64)

In [38]:
arra3.ndim

3

In [39]:
arra3[[0,0,0]]

array([[[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
arra = np.arange(32).reshape(8,4)

In [41]:
arra[[1,2,3],[0,1,3]]

array([ 4,  9, 15])

In [42]:
arrays1 = np.random.randn(6,3)

In [43]:
np.dot(arrays1.T,arrays1)

array([[ 4.76503209,  0.87663885,  4.22848315],
       [ 0.87663885,  8.45963163,  2.33499507],
       [ 4.22848315,  2.33499507,  4.78816721]])

In [44]:
arr = np.arange(16).reshape(2,2,4)

arr.transpose(1,0,2)

In [45]:
array = np.arange(8).reshape(2,4)

In [46]:
array


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
### Universal Functions

In [48]:
arr = np.arange(10)

In [49]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [50]:
np.dtype

numpy.dtype

In [51]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [52]:
x = np.random.randn(8)

In [53]:
x

array([-1.14806849,  0.31993461, -0.77320243, -0.12112032,  1.18887016,
        0.32694492,  0.83042   ,  0.17302451])

In [54]:
y = np.random.randn(8)

In [55]:
np.maximum(x,y)

array([-0.74652697,  0.31993461, -0.41295933, -0.12112032,  1.18887016,
        0.86240542,  0.83042   ,  0.25532919])

In [56]:
np.abs(9.9)

9.9000000000000004

In [57]:
np.fabs(9.9)

9.9000000000000004

In [58]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
### sign ceil floor rint modf isnan isinf cos
### cos cosh sin sinh
### arccos arcsin arctan logical_not

In [60]:
### add subtract multiply divide power maximum minimum

In [61]:
arr = np.random.randn(5,3)

In [62]:
arr

array([[ 0.43018648, -0.35735488,  1.41399711],
       [ 0.6087513 ,  0.44715526,  0.85396515],
       [-0.3583003 , -2.94979906,  0.08930592],
       [-0.68819915,  1.03499032, -0.78619043],
       [ 1.03580081, -1.01745393, -0.71906367]])

In [63]:
arr.sort(0)

In [64]:
arr

array([[-0.68819915, -2.94979906, -0.78619043],
       [-0.3583003 , -1.01745393, -0.71906367],
       [ 0.43018648, -0.35735488,  0.08930592],
       [ 0.6087513 ,  0.44715526,  0.85396515],
       [ 1.03580081,  1.03499032,  1.41399711]])

In [65]:
names = np.array(['bob','lol','abhi','ruby','c##', 'hadoop', 'spark','python','numpy'])

In [66]:
np.unique(names)

array(['abhi', 'bob', 'c##', 'hadoop', 'lol', 'numpy', 'python', 'ruby',
       'spark'], 
      dtype='<U6')

In [67]:
from collections import Counter
Counter(names)

Counter({'abhi': 1,
         'bob': 1,
         'c##': 1,
         'hadoop': 1,
         'lol': 1,
         'numpy': 1,
         'python': 1,
         'ruby': 1,
         'spark': 1})

In [69]:
### intersectid(x,y) unionid intid setdiffid setxorid
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])
condition = np.array([True,True,False,False])

In [71]:
answer2 = np.where(condition,A,B)

In [72]:
answer2

array([  1,   2, 300, 400])

In [73]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [74]:
arr.sum()

45

In [75]:
arr.sum(0) # No median and mode

array([12, 15, 18])

In [76]:
arr.mean()

5.0

In [77]:
arr.var()

6.666666666666667

In [78]:
arr.std()

2.5819888974716112

In [79]:
%pwd

'/home/ubuntu/workspace/Ipython/Untitled Folder'

In [80]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [81]:
np.insert(a,1,5)

array([1, 5, 1, 2, 2, 3, 3])

In [82]:
np.insert(a,1,5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [83]:
arr = np.arange(5)

In [84]:
np.save('my_array', arr)

In [85]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [86]:
np.savez('two_arrays.npz',x=arr,y=arr)


In [87]:
archive_array = np.load('two_arrays.npz')

In [88]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [89]:
archive_array['y']

array([0, 1, 2, 3, 4])

In [90]:
arr = np.array([[1,2,3],[4,5,6]])

In [91]:
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [92]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')

In [94]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])